---
- name: Install NGINX on Red Hat
  hosts: ['4225a859242c.mylabserver.com','4225a859243c.mylabserver.com','4225a859244c.mylabserver.com']
  become: true
  vars:
    ansible_user: man-sinh-lee
  tasks:
    - name: Update package cache
      package:
        name: epel-release
        state: present

    - name: Install NGINX
      package:
        name: nginx
        state: present

    - name: Start NGINX service
      service:
        name: nginx
        state: started
        enabled: yes
